apiVersion: apps/v1
kind: Deployment
metadata:
  name: room9-backend
spec:
  selector:
    matchLabels:
      name: room9-backend
  template:
    metadata:
      labels:
        name: room9-backend
    spec:
      containers:
        - image: hsju0202/room9-backend:test3
          name: room9-backend
          ports:
            - containerPort: 8080
              name: room9-backend
